---
openapi: 3.0.3
info:
  title: rspec-openapi-test
  version: 1.0.0
servers:
- url: http://localhost:3000
- url: http://localhost:4000
paths:
  "/api/v1/tables":
    get:
      summary: index
      tags:
      - てーぶるのいんでっくす
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
        example: 1
      - name: per
        in: query
        required: false
        schema:
          type: integer
        example: 10
      responses:
        '200':
          description: ここに説明入ります
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    memo:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - title
                  - memo
                  - created_at
                  - updated_at
              example:
              - id: 497
                title: weasel
                memo: Berilac Brandybuck
                created_at: '2023-10-20T05:02:48.998Z'
                updated_at: '2023-10-20T05:02:48.998Z'
              - id: 498
                title: goldfish
                memo: Tanta Hornblower
                created_at: '2023-10-20T05:02:49.033Z'
                updated_at: '2023-10-20T05:02:49.033Z'
              - id: 499
                title: koala
                memo: Golasgil
                created_at: '2023-10-20T05:02:49.034Z'
                updated_at: '2023-10-20T05:02:49.034Z'
              - id: 500
                title: eagle
                memo: Narmacil
                created_at: '2023-10-20T05:02:49.035Z'
                updated_at: '2023-10-20T05:02:49.035Z'
              - id: 501
                title: fly
                memo: Minastan
                created_at: '2023-10-20T05:02:49.036Z'
                updated_at: '2023-10-20T05:02:49.036Z'
              - id: 502
                title: fish
                memo: Bilbo Baggins
                created_at: '2023-10-20T05:02:49.036Z'
                updated_at: '2023-10-20T05:02:49.036Z'
              - id: 503
                title: skunk
                memo: Lily Baggins
                created_at: '2023-10-20T05:02:49.037Z'
                updated_at: '2023-10-20T05:02:49.037Z'
              - id: 504
                title: monkey
                memo: Grimbeorn
                created_at: '2023-10-20T05:02:49.038Z'
                updated_at: '2023-10-20T05:02:49.038Z'
              - id: 505
                title: otter
                memo: Isengrim
                created_at: '2023-10-20T05:02:49.038Z'
                updated_at: '2023-10-20T05:02:49.038Z'
              - id: 506
                title: fox
                memo: Gimilkhâd
                created_at: '2023-10-20T05:02:49.039Z'
                updated_at: '2023-10-20T05:02:49.039Z'
    post:
      summary: create
      tags:
      - てーぶるのいんでっくす
      parameters:
      - name: X-Authorization-Token
        in: header
        required: true
        schema:
          type: string
        example: k0kubun
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                memo:
                  type: string
              required:
              - memo
            example:
              title: foo
              memo: bag
      responses:
        '200':
          description: createの説明がここに説明入ります
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  memo:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - memo
                - created_at
                - updated_at
              example:
                id: 517
                title: foo
                memo: bag
                created_at: '2023-10-20T05:02:49.072Z'
                updated_at: '2023-10-20T05:02:49.072Z'
        '400':
          description: titleがない場合400が返ります
